set identity_insert [Products] on


/*
Lipsticks
*/
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (1,97,'Maybelline Color Sensational Vivid Matte Liquid Lip Colour','lipstick','maybelline',20,12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. \nFormula is comfortable and creamy with a smooth feel upon application. \nWith full color coverage, the result is a rich, intense lip look in a \nrange of colors from Nude Flush to Electric Pink to Vivid Violet.Features: Lip color glides on smooth to a matte finishInfused with pure pigments for high-impact colorCreamy liquid base for a soft, cushiony feel.','https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png','Nude Thrill','#AC7773');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (2,97,'Maybelline Color Sensational Vivid Matte Liquid Lip Colour','lipstick','maybelline',20,12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. \nFormula is comfortable and creamy with a smooth feel upon application. \nWith full color coverage, the result is a rich, intense lip look in a \nrange of colors from Nude Flush to Electric Pink to Vivid Violet.Features: Lip color glides on smooth to a matte finishInfused with pure pigments for high-impact colorCreamy liquid base for a soft, cushiony feel.','https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png','Nude Flush','#BD7A80');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (3,97,'Maybelline Color Sensational Vivid Matte Liquid Lip Colour','lipstick','maybelline',20,12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. \nFormula is comfortable and creamy with a smooth feel upon application. \nWith full color coverage, the result is a rich, intense lip look in a \nrange of colors from Nude Flush to Electric Pink to Vivid Violet.Features: Lip color glides on smooth to a matte finishInfused with pure pigments for high-impact colorCreamy liquid base for a soft, cushiony feel.','https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png','Pink Charge','#D65F84');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (4,97,'Maybelline Color Sensational Vivid Matte Liquid Lip Colour','lipstick','maybelline',20,12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. \nFormula is comfortable and creamy with a smooth feel upon application. \nWith full color coverage, the result is a rich, intense lip look in a \nrange of colors from Nude Flush to Electric Pink to Vivid Violet.Features: Lip color glides on smooth to a matte finishInfused with pure pigments for high-impact colorCreamy liquid base for a soft, cushiony feel.','https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png','Electric Pink','#D73D8C');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(5,97, 'Maybelline Color Sensational Vivid Matte Liquid Lip Colour', 'lipstick', 'maybelline', 20, 12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. Formula is comfortable and creamy with a smooth feel upon application.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png', 'Fuchsia Ecstasy ','#B12156');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(6,97, 'Maybelline Color Sensational Vivid Matte Liquid Lip Colour', 'lipstick', 'maybelline', 20, 12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. Formula is comfortable and creamy with a smooth feel upon application.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png', 'Orange Shot ','#BC2830');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(7, 97, 'Maybelline Color Sensational Vivid Matte Liquid Lip Colour', 'lipstick', 'maybelline', 20, 12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. Formula is comfortable and creamy with a smooth feel upon application.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png', 'Rebel Red ','#B7233B');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(8, 97, 'Maybelline Color Sensational Vivid Matte Liquid Lip Colour', 'lipstick', 'maybelline', 20, 12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. Formula is comfortable and creamy with a smooth feel upon application.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png', 'Berry Boost ','#8C1F48');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(9, 97, 'Maybelline Color Sensational Vivid Matte Liquid Lip Colour', 'lipstick', 'maybelline', 20, 12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. Formula is comfortable and creamy with a smooth feel upon application.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png', 'Vivid Violet ','#542A71');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(10, 97, 'Maybelline Color Sensational Vivid Matte Liquid Lip Colour', 'lipstick', 'maybelline', 20, 12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. Formula is comfortable and creamy with a smooth feel upon application.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png', 'Possessed Plum ','#300B28');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(11, 89, 'Maybelline Color Sensational Rebel Bloom Lipcolour ', 'lipstick', 'maybelline', 20, 9.99, ' Maybelline Color Sensationalr Rebel Bloom lipstick offers vivacious pastel in a super-saturated lipcolour.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/fb9e6485500135d94163577da4c3579b_ra,w158,h184_pa,w158,h184.png', 'Barely Bloomed ','#db967f');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(12, 89, 'Maybelline Color Sensational Rebel Bloom Lipcolour ', 'lipstick', 'maybelline', 20, 9.99, ' Maybelline Color Sensationalr Rebel Bloom lipstick offers vivacious pastel in a super-saturated lipcolour.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/fb9e6485500135d94163577da4c3579b_ra,w158,h184_pa,w158,h184.png', 'Blushing Bud ','#d37d79');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(13, 89, 'Maybelline Color Sensational Rebel Bloom Lipcolour ', 'lipstick', 'maybelline', 20, 9.99, ' Maybelline Color Sensationalr Rebel Bloom lipstick offers vivacious pastel in a super-saturated lipcolour.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/fb9e6485500135d94163577da4c3579b_ra,w158,h184_pa,w158,h184.png', 'Coral Burst ','#f05b4a');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(14, 89, 'Maybelline Color Sensational Rebel Bloom Lipcolour ', 'lipstick', 'maybelline', 20, 9.99, ' Maybelline Color Sensationalr Rebel Bloom lipstick offers vivacious pastel in a super-saturated lipcolour.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/fb9e6485500135d94163577da4c3579b_ra,w158,h184_pa,w158,h184.png', 'Lilac Flush ','#cd86b0');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(15, 89, 'Maybelline Color Sensational Rebel Bloom Lipcolour ', 'lipstick', 'maybelline', 20, 9.99, 'Maybelline Color Sensationalr Rebel Bloom lipstick offers vivacious pastel in a super-saturated lipcolour.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/fb9e6485500135d94163577da4c3579b_ra,w158,h184_pa,w158,h184.png', 'Petal Pink ','#ff8f9d');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(16, 89, 'Maybelline Color Sensational Rebel Bloom Lipcolour ', 'lipstick', 'maybelline', 20, 9.99, 'Maybelline Color Sensationalr Rebel Bloom lipstick offers vivacious pastel in a super-saturated lipcolour.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/fb9e6485500135d94163577da4c3579b_ra,w158,h184_pa,w158,h184.png', 'Rose Rush ','#bd2629');
-- Maybelline eyeshadow
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (17,291,'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather','eyeshadow','maybelline',20,5.99,'Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their most intense, long-lasting colour saturation. The cream formula glides on without creasing and keeps colour vibrant.Ophthalmologist-tested. Safe for sensitive eyes and contact lens wearers. For added drama, darken as desired. ','https://d3t32hsnjxo7q6.cloudfront.net/i/c2ddacc79f4fdd3d23664581c76546bc_ra,w158,h184_pa,w158,h184.png','Bad to the Bronze','#ab897d');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (18,291,'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather','eyeshadow','maybelline',20,5.99,'Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their most intense, long-lasting colour saturation. The cream formula glides on without creasing and keeps colour vibrant.Ophthalmologist-tested. Safe for sensitive eyes and contact lens wearers. For added drama, darken as desired. ','https://d3t32hsnjxo7q6.cloudfront.net/i/c2ddacc79f4fdd3d23664581c76546bc_ra,w158,h184_pa,w158,h184.png','Tenacious Teal','#1d8493');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (19,291,'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather','eyeshadow','maybelline',20,5.99,'Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their most intense, long-lasting colour saturation. The cream formula glides on without creasing and keeps colour vibrant.Ophthalmologist-tested. Safe for sensitive eyes and contact lens wearers. For added drama, darken as desired. ','https://d3t32hsnjxo7q6.cloudfront.net/i/c2ddacc79f4fdd3d23664581c76546bc_ra,w158,h184_pa,w158,h184.png','Too Cool','#d3cfcc');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (20,291,'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather','eyeshadow','maybelline',20,5.99,'Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their most intense, long-lasting colour saturation. The cream formula glides on without creasing and keeps colour vibrant.Ophthalmologist-tested. Safe for sensitive eyes and contact lens wearers. For added drama, darken as desired. ','https://d3t32hsnjxo7q6.cloudfront.net/i/c2ddacc79f4fdd3d23664581c76546bc_ra,w158,h184_pa,w158,h184.png','Tough as Taupe','#81726D');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(21, 309, 'Maybelline Expert Wear Eye Shadow Quad ', 'eyeshadow', 'maybelline', 20, 8.99, 'Easy to use, lots to choose!Maybelline Expert Wear Eye Shadow Quads ave 4 coordinating shades with step by step application guidemakes shadow easier than ever. The eyeshadows glide on effortlessly withsuperior smoothness and the velvet-tip applicator blends withouttugging or pulling.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c924006882e8e313d445a3a5394e4729_ra,w158,h184_pa,w158,h184.png', '','');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(22, 307, 'Maybelline Eyestudio Color Tattoo Concentrated Crayon', 'eyeshadow', 'maybelline', 20, 10.99, 'Maybelline Eyestudio Color Tattoo Concentrated Crayons give you high-intensity color that looks vibrant all-day long.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/3f9f894b56e0616e44c5ee01dea45217_ra,w158,h184_pa,w158,h184.png', 'Audacious Asphalt ','#515552');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(23,307, 'Maybelline Eyestudio Color Tattoo Concentrated Crayon', 'eyeshadow', 'maybelline', 20, 10.99, 'Maybelline Eyestudio Color Tattoo Concentrated Crayons give you high-intensity color that looks vibrant all-day long.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/3f9f894b56e0616e44c5ee01dea45217_ra,w158,h184_pa,w158,h184.png', 'Barely Beige ','#D8BFAC');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(24,307, 'Maybelline Eyestudio Color Tattoo Concentrated Crayon', 'eyeshadow', 'maybelline', 20, 10.99, 'Maybelline Eyestudio Color Tattoo Concentrated Crayons give you high-intensity color that looks vibrant all-day long.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/3f9f894b56e0616e44c5ee01dea45217_ra,w158,h184_pa,w158,h184.png', 'Bronze Truffle ','#B89A89');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(25,307, 'Maybelline Eyestudio Color Tattoo Concentrated Crayon', 'eyeshadow', 'maybelline', 20, 10.99, 'Maybelline Eyestudio Color Tattoo Concentrated Crayons give you high-intensity color that looks vibrant all-day long.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/3f9f894b56e0616e44c5ee01dea45217_ra,w158,h184_pa,w158,h184.png', 'Charcoal Chrome ','#706A70');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(26,307, 'Maybelline Eyestudio Color Tattoo Concentrated Crayon', 'eyeshadow', 'maybelline', 20, 10.99, 'Maybelline Eyestudio Color Tattoo Concentrated Crayons give you high-intensity color that looks vibrant all-day long.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/3f9f894b56e0616e44c5ee01dea45217_ra,w158,h184_pa,w158,h184.png', 'Creamy Chocolate ','#5C3B27');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(27,307, 'Maybelline Eyestudio Color Tattoo Concentrated Crayon', 'eyeshadow', 'maybelline', 20, 10.99, 'Maybelline Eyestudio Color Tattoo Concentrated Crayons give you high-intensity color that looks vibrant all-day long.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/3f9f894b56e0616e44c5ee01dea45217_ra,w158,h184_pa,w158,h184.png', 'Gold Rush ','#DDBA89');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(28,307, 'Maybelline Eyestudio Color Tattoo Concentrated Crayon', 'eyeshadow', 'maybelline', 20, 10.99, 'Maybelline Eyestudio Color Tattoo Concentrated Crayons give you high-intensity color that looks vibrant all-day long.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/3f9f894b56e0616e44c5ee01dea45217_ra,w158,h184_pa,w158,h184.png', 'Grey Crystal ','#8E8C86');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(29,307, 'Maybelline Eyestudio Color Tattoo Concentrated Crayon', 'eyeshadow', 'maybelline', 20, 10.99, 'Maybelline Eyestudio Color Tattoo Concentrated Crayons give you high-intensity color that looks vibrant all-day long.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/3f9f894b56e0616e44c5ee01dea45217_ra,w158,h184_pa,w158,h184.png', 'Lavish Lavender ','#7D6F7D');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(30,307, 'Maybelline Eyestudio Color Tattoo Concentrated Crayon', 'eyeshadow', 'maybelline', 20, 10.99, 'Maybelline Eyestudio Color Tattoo Concentrated Crayons give you high-intensity color that looks vibrant all-day long.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/3f9f894b56e0616e44c5ee01dea45217_ra,w158,h184_pa,w158,h184.png', 'Lilac Lust ','#957B83');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(31,307, 'Maybelline Eyestudio Color Tattoo Concentrated Crayon', 'eyeshadow', 'maybelline', 20, 10.99, 'Maybelline Eyestudio Color Tattoo Concentrated Crayons give you high-intensity color that looks vibrant all-day long.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/3f9f894b56e0616e44c5ee01dea45217_ra,w158,h184_pa,w158,h184.png', 'Pink Parfait ','#E5AEB9');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(32,295, 'Maybelline The Nudes Eye Shadow Palette', 'eyeshadow', 'maybelline', 4, 17.99, 'Maybelline The Nudes Eye Shadow Palette lets you create looks from day to night. Deep to light. So try it out and create your ideal eye look today!', 'https://d3t32hsnjxo7q6.cloudfront.net/i/201350fd3e173307ade44520dc87d8fb_ra,w158,h184_pa,w158,h184.png', '','');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(33,291, 'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather', 'eyeshadow', 'maybelline', 20, 8.99, 'So rich. So creamy. Only Maybellines cream gel eye shadow formula gets the', 'https://d3t32hsnjxo7q6.cloudfront.net/i/cf21d194ab14ee3c527d02682c358a7a_ra,w158,h184_pa,w158,h184.png', 'Chocolate Suede (95) ','#8A665B');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(34,291, 'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather', 'eyeshadow', 'maybelline', 20, 8.99, 'So rich. So creamy. Only Maybellines cream gel eye shadow formula gets the', 'https://d3t32hsnjxo7q6.cloudfront.net/i/cf21d194ab14ee3c527d02682c358a7a_ra,w158,h184_pa,w158,h184.png', 'Creamy Beige (80) ','#BD9786');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(35,291, 'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather', 'eyeshadow', 'maybelline', 20, 8.99, 'So rich. So creamy. Only Maybellines cream gel eye shadow formula gets the', 'https://d3t32hsnjxo7q6.cloudfront.net/i/cf21d194ab14ee3c527d02682c358a7a_ra,w158,h184_pa,w158,h184.png', 'Deep Forest (85) ','#98907A');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(36,291, 'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather', 'eyeshadow', 'maybelline', 20, 8.99, 'So rich. So creamy. Only Maybellines cream gel eye shadow formula gets the', 'https://d3t32hsnjxo7q6.cloudfront.net/i/cf21d194ab14ee3c527d02682c358a7a_ra,w158,h184_pa,w158,h184.png', 'Dramatic Black (100) ','#484A4E');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(37,291, 'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather', 'eyeshadow', 'maybelline', 20, 8.99, ' So rich. So creamy. Only Maybellines cream gel eye shadow formula gets the', 'https://d3t32hsnjxo7q6.cloudfront.net/i/cf21d194ab14ee3c527d02682c358a7a_ra,w158,h184_pa,w158,h184.png', 'Vintage Plum (90) ','#B196A6');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(38,286, 'Maybelline The Nudes Eyeshadow Palette in The Blushed Nudes', 'eyeshadow', 'maybelline', 20, 17.99, 'Create looks from day to night and deep to light with Maybellines The Blushed Nudes Eyeshadow Palette.Features:', 'https://d3t32hsnjxo7q6.cloudfront.net/i/49d98e112e77d2a9a0c8fad28df89a1e_ra,w158,h184_pa,w158,h184.png', '','');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(39,273, 'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow ', 'eyeshadow', 'maybelline', 20, 8.99, 'Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their mo', 'https://d3t32hsnjxo7q6.cloudfront.net/i/58d07d24e39142e0c5a178b00b6b31f1_ra,w158,h184_pa,w158,h184.png', 'Inked in Pink (55) ','#fdd3d2');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(40,273, 'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow ', 'eyeshadow', 'maybelline', 20, 8.99, 'Dare to wear 24HR shadow!Maybellines Color Tattoo Cream GelShadow uses ink technology for their mo', 'https://d3t32hsnjxo7q6.cloudfront.net/i/58d07d24e39142e0c5a178b00b6b31f1_ra,w158,h184_pa,w158,h184.png', 'Silver Strike (60) ','#c5c7c8');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(41,273, 'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow ', 'eyeshadow', 'maybelline', 20, 8.99, 'Dare to wear 24HR shadow!Maybellines Color Tattoo Cream GelShadow uses ink technology for their mo', 'https://d3t32hsnjxo7q6.cloudfront.net/i/58d07d24e39142e0c5a178b00b6b31f1_ra,w158,h184_pa,w158,h184.png', 'Barely Branded (70) ','#f2caad');
/*
Maybelline eyeliners
*/
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (42,232,'Maybelline Line Express Eyeliner','eyeliner','maybelline',20,7.29, 'Maybelline Line Express Eyeliner"s intense color formula + smart tip smudger makes this liner glide on smoothly and is easy to apply with just one stroke.Features: Creamy formula delivers intense colorContour smudger makes blending easyAll-day wearSafe for sensitive eyes and ophthalmologist-testedContact lens safe','https://d3t32hsnjxo7q6.cloudfront.net/i/4e88f928ad91c88e2ecb8596431ce799_ra,w158,h184_pa,w158,h184.png','','');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (43,229,'Maybelline Unstoppable Eyeline','eyeliner','maybelline',20,8.99, 'Unstoppable Eyeliner allows ultra-smooth application for defined lines and eyes.\nIt is a self-sharpening mechanical pencil, and will hold your look in place all day long.\nWaterproof.\nOphthalmologist tested, contact lens safe for sensitive eyes.\n','https://d3t32hsnjxo7q6.cloudfront.net/i/bab89a9fe13b34235e0dd1f4f44c05cf_ra,w158,h184_pa,w158,h184.png','Onyx ','#736364');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (44,229,'Maybelline Unstoppable Eyeline','eyeliner','maybelline',20,8.99, 'Unstoppable Eyeliner allows ultra-smooth application for defined lines and eyes.\nIt is a self-sharpening mechanical pencil, and will hold your look in place all day long.\nWaterproof.\nOphthalmologist tested, contact lens safe for sensitive eyes.\n','https://d3t32hsnjxo7q6.cloudfront.net/i/bab89a9fe13b34235e0dd1f4f44c05cf_ra,w158,h184_pa,w158,h184.png','Pewter ','#797B7D');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(45,225, 'Maybelline Color Show Kohl Liner', 'eyeliner', 'maybelline', 220, 5.99, 'So rich. So creamy. Only Maybellines cream gel eye shadow formula gets the look of couture leather so right!', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c2fcd605bbf3941b521fb74bfa942ac6_ra,w158,h184_pa,w158,h184.png', 'Beauty Blue ','#2e4064');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(46,225, 'Maybelline Color Show Kohl Liner', 'eyeliner', 'maybelline', 220, 5.99, 'So rich. So creamy. Only Maybellines cream gel eye shadow formula gets the look of couture leather so right!', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c2fcd605bbf3941b521fb74bfa942ac6_ra,w158,h184_pa,w158,h184.png', 'Chocolate Chip ','#56403a');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(47,225, 'Maybelline Color Show Kohl Liner', 'eyeliner', 'maybelline', 220, 5.99, 'So rich. So creamy. Only Maybellines cream gel eye shadow formula gets the look of couture leather so right!', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c2fcd605bbf3941b521fb74bfa942ac6_ra,w158,h184_pa,w158,h184.png', 'Edgy Emerald ','#008687');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(48,225, 'Maybelline Color Show Kohl Liner', 'eyeliner', 'maybelline', 220, 5.99, 'So rich. So creamy. Only Maybellines cream gel eye shadow formula gets the look of couture leather so right!', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c2fcd605bbf3941b521fb74bfa942ac6_ra,w158,h184_pa,w158,h184.png', 'Marvelous Maroon ','#854f58');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(49,225, 'Maybelline Color Show Kohl Liner', 'eyeliner', 'maybelline', 220, 5.99, 'So rich. So creamy. Only Maybellines cream gel eye shadow formula gets the look of couture leather so right!', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c2fcd605bbf3941b521fb74bfa942ac6_ra,w158,h184_pa,w158,h184.png', 'Sparkle Grey ','#837163');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(50,225, 'Maybelline Color Show Kohl Liner', 'eyeliner', 'maybelline', 220, 5.99, 'So rich. So creamy. Only Maybellines cream gel eye shadow formula gets the look of couture leather so right!', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c2fcd605bbf3941b521fb74bfa942ac6_ra,w158,h184_pa,w158,h184.png', 'Turquoise Flash ','#00849d');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(51,225, 'Maybelline Color Show Kohl Liner', 'eyeliner', 'maybelline', 220, 5.99, 'Maybelline Color Show Kohl Liner is the hottest new way to create statement eyes!', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c2fcd605bbf3941b521fb74bfa942ac6_ra,w158,h184_pa,w158,h184.png', 'Ultra Black ','#000000');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(52,225, 'Maybelline Color Show Kohl Liner', 'eyeliner', 'maybelline', 220, 5.99, 'Maybelline Color Show Kohl Liner is the hottest new way to create statement eyes!', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c2fcd605bbf3941b521fb74bfa942ac6_ra,w158,h184_pa,w158,h184.png', 'Vibrant Violet ','#574c7c');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(53,221, 'Maybelline Eye Studio Master Graphic in Striking Black', 'eyeliner', 'maybelline', 220, 11.99, 'Eye Studio Master Graphic Liquid Liner from Maybelline New York. Love the graphic look? This genius eyeliner automatically draws the boldest line with the sharpest edge!', 'https://d3t32hsnjxo7q6.cloudfront.net/i/9c98f99f2033bb942286fa1bb32b4c51_ra,w158,h184_pa,w158,h184.png', '','');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(54,179, 'Maybelline EyeStudio Master Precise Ink Pen Eyeliner', 'eyeliner', 'maybelline', 220, 11.99, 'Experience the new generation of liquid liner from Maybelline! Safe for sensitive eyes and ophthalmologist-testedContact lens safe.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/6edd2cadd1894a94f264ceb19f3d344b_ra,w158,h184_pa,w158,h184.png', '','');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(55,177, 'Maybelline Line Stiletto Ultimate Precision Liquid Eyeliner', 'eyeliner', 'maybelline', 220, 10.29, 'Easily Creates Slender Lines.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/350d6c6c2fa3add8ee40189cd19bfe0a_ra,w158,h184_pa,w158,h184.png', 'Blackest Black ','#000000');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(56,177, 'Maybelline Line Stiletto Ultimate Precision Liquid Eyeliner', 'eyeliner', 'maybelline', 220, 10.29, 'Easily Creates Slender Lines.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/350d6c6c2fa3add8ee40189cd19bfe0a_ra,w158,h184_pa,w158,h184.png', 'Brown Black ','#4E2F2F');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(57,172, 'Maybelline Liquid Eyeliner', 'eyeliner', 'maybelline', 220, 10.99, 'Waterproof Liquid Eyeliner draws intense lining in an instant.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/316d25ac5676470d83612b9391678b0d_ra,w158,h184_pa,w158,h184.jpeg', 'Black ','#06090A');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(58,170, 'Maybelline Eye Studio Lasting Drama Gel Eyeliner', 'eyeliner', 'maybelline', 220, 11.99, 'Maybelline Eye Studio Lasting Drama Gel Eyeliner gives you smudge-proof lines that are waterproof for 24 hours.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/2054f702d243c286219e0330af836bf5_ra,w158,h184_pa,w158,h184.png', 'Blackest Black 950 ','#000000');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(59,170, 'Maybelline Eye Studio Lasting Drama Gel Eyeliner', 'eyeliner', 'maybelline', 220, 11.99, 'Maybelline Eye Studio Lasting Drama Gel Eyeliner gives you smudge-proof lines that are waterproof for 24 hours.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/2054f702d243c286219e0330af836bf5_ra,w158,h184_pa,w158,h184.png', 'Brown 952 ','#60423B');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(60,170, 'Maybelline Eye Studio Lasting Drama Gel Eyeliner', 'eyeliner', 'maybelline', 220, 11.99, 'Maybelline Eye Studio Lasting Drama Gel Eyeliner gives you smudge-proof lines that are waterproof for 24 hours.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/2054f702d243c286219e0330af836bf5_ra,w158,h184_pa,w158,h184.png', 'Charcoal 954 ','#4A484B');
/*
Maybelline foundation
*/
insert into [Products] ([ProductID], [API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (61, 380, 'Maybelline Fit Me Shine-Free Foundation Stic','foundation', 'maybelline', 20, 10.99, 'Get flawless, shine-free skin instantly and on-the-go for tailor-made mattifying coverage.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/d04e7c2ed65dabe1dca4eed9aa268e95_ra,w158,h184_pa,w158,h184.png', 'Porcelain (110)', '#FFE4C6');
insert into [Products] ([ProductID], [API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (62, 380, 'Maybelline Fit Me Shine-Free Foundation Stic', 'foundation','maybelline', 20, 10.99, 'Get flawless, shine-free skin instantly and on-the-go for tailor-made mattifying coverage.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/d04e7c2ed65dabe1dca4eed9aa268e95_ra,w158,h184_pa,w158,h184.png', 'Ivory (115)', '#FFE5C1');
insert into [Products] ([ProductID], [API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (63, 380, 'Maybelline Fit Me Shine-Free Foundation Stic', 'foundation','maybelline', 20, 10.99, 'Get flawless, shine-free skin instantly and on-the-go for tailor-made mattifying coverage.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/d04e7c2ed65dabe1dca4eed9aa268e95_ra,w158,h184_pa,w158,h184.png', 'Classic Ivory (120)', '#FFD9B9');
insert into [Products] ([ProductID], [API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (64, 380, 'Maybelline Fit Me Shine-Free Foundation Stic','foundation' ,'maybelline', 20, 10.99, 'Get flawless, shine-free skin instantly and on-the-go for tailor-made mattifying coverage.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/d04e7c2ed65dabe1dca4eed9aa268e95_ra,w158,h184_pa,w158,h184.png', 'Natural Beige (220)', '#FACFA8');
insert into [Products] ([ProductID], [API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (65, 380, 'Maybelline Fit Me Shine-Free Foundation Stic','foundation' ,'maybelline', 20, 10.99, 'Get flawless, shine-free skin instantly and on-the-go for tailor-made mattifying coverage.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/d04e7c2ed65dabe1dca4eed9aa268e95_ra,w158,h184_pa,w158,h184.png', 'Toffee (330)', '#D39B70');
insert into [Products] ([ProductID], [API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (66, 380, 'Maybelline Fit Me Shine-Free Foundation Stic', 'foundation','maybelline', 20, 10.99, 'Get flawless, shine-free skin instantly and on-the-go for tailor-made mattifying coverage.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/d04e7c2ed65dabe1dca4eed9aa268e95_ra,w158,h184_pa,w158,h184.png', 'Coconut (355)', '#CA8B67');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(67,379, 'Maybelline Dream Matte Mousse Foundation', 'foundation', 'maybelline', 20, 14.79, 'Maybelline Dream Matte Mouse Foundation is a revolutionary air-soft mousse that provides perfecting coverage for 100% velvet-matte complexion.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/029889b345c76a70e8bb978b73ed1a87_ra,w158,h184_pa,w158,h184.png', 'Classic Ivory ','#f3d7b3');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(68,379, 'Maybelline Dream Matte Mousse Foundation', 'foundation', 'maybelline', 20, 14.79, 'Maybelline Dream Matte Mouse Foundation is a revolutionary air-soft mousse that provides perfecting coverage for 100% velvet-matte complexion.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/029889b345c76a70e8bb978b73ed1a87_ra,w158,h184_pa,w158,h184.png', 'Light Beige ','#dfc5a8');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(69,379, 'Maybelline Dream Matte Mousse Foundation', 'foundation', 'maybelline', 20, 14.79, 'Maybelline Dream Matte Mouse Foundation is a revolutionary air-soft mousse that provides perfecting coverage for 100% velvet-matte complexion.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/029889b345c76a70e8bb978b73ed1a87_ra,w158,h184_pa,w158,h184.png', 'Nude ','#edd3ac');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(70,379, 'Maybelline Dream Matte Mousse Foundation', 'foundation', 'maybelline', 20, 14.79, 'Maybelline Dream Matte Mouse Foundation is a revolutionary air-soft mousse that provides perfecting coverage for 100% velvet-matte complexion.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/029889b345c76a70e8bb978b73ed1a87_ra,w158,h184_pa,w158,h184.png', 'Porcelain Ivory ','#f5dfc3');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(71,379, 'Maybelline Dream Matte Mousse Foundation', 'foundation', 'maybelline', 20, 14.79, 'Maybelline Dream Matte Mouse Foundation is a revolutionary air-soft mousse that provides perfecting coverage for 100% velvet-matte complexion.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/029889b345c76a70e8bb978b73ed1a87_ra,w158,h184_pa,w158,h184.png', 'Pure Beige ','#d9bcaf');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(72,379, 'Maybelline Dream Matte Mousse Foundation', 'foundation', 'maybelline', 20, 14.79, 'Maybelline Dream Matte Mouse Foundation is a revolutionary air-soft mousse that provides perfecting coverage for 100% velvet-matte complexion.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/029889b345c76a70e8bb978b73ed1a87_ra,w158,h184_pa,w158,h184.png', 'Sandy Beige ','#d8bda8');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(73,366, 'Maybelline Mineral Power Natural Perfecting Powder Foundation', 'foundation', 'maybelline', 4, 14.99, 'Why Youll Love ItMineral Power Powder Foundation with micro-minerals provides a more natural, healthier, luminous look.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c77ad2da76259cfd67a9a9432f635bfb_ra,w158,h184_pa,w158,h184.png', 'Classic Ivory ','#FFD59E');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(74,354, 'Maybelline Dream Velvet Foundation', 'foundation', 'maybelline', 20, 18.49, 'This Maybelline Dream Velvet Foundation is a refreshing gel-whipped foundation that leaves complexion perfected and smooth with a velvety, soft-matte finish.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/24517c6c81c92eda31cd32b6327c1298_ra,w158,h184_pa,w158,h184.png', 'Caramel ','#D39D7B');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(75,354, 'Maybelline Dream Velvet Foundation', 'foundation', 'maybelline', 20, 18.49, 'This Maybelline Dream Velvet Foundation is a refreshing gel-whipped foundation that leaves complexion perfected and smooth with a velvety, soft-matte finish.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/24517c6c81c92eda31cd32b6327c1298_ra,w158,h184_pa,w158,h184.png', 'Classic Ivory ','#F5CAB9');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(76,354, 'Maybelline Dream Velvet Foundation', 'foundation', 'maybelline', 20, 18.49, 'This Maybelline Dream Velvet Foundation is a refreshing gel-whipped foundation that leaves complexion perfected and smooth with a velvety, soft-matte finish.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/24517c6c81c92eda31cd32b6327c1298_ra,w158,h184_pa,w158,h184.png', 'Coconut ','#B37560');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(77,354, 'Maybelline Dream Velvet Foundation', 'foundation', 'maybelline', 20, 18.49, 'This Maybelline Dream Velvet Foundation is a refreshing gel-whipped foundation that leaves complexion perfected and smooth with a velvety, soft-matte finish.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/24517c6c81c92eda31cd32b6327c1298_ra,w158,h184_pa,w158,h184.png', 'Creamy Natural  ','#F3BEAC');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(78,354, 'Maybelline Dream Velvet Foundation', 'foundation', 'maybelline', 20, 18.49, 'This Maybelline Dream Velvet Foundation is a refreshing gel-whipped foundation that leaves complexion perfected and smooth with a velvety, soft-matte finish.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/24517c6c81c92eda31cd32b6327c1298_ra,w158,h184_pa,w158,h184.png', 'Honey Beige  ','#E4A890');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(79,354, 'Maybelline Dream Velvet Foundation', 'foundation', 'maybelline', 20, 18.49, 'This Maybelline Dream Velvet Foundation is a refreshing gel-whipped foundation that leaves complexion perfected and smooth with a velvety, soft-matte finish.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/24517c6c81c92eda31cd32b6327c1298_ra,w158,h184_pa,w158,h184.png', 'Ivory ','#F6D2BC');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(80,354, 'Maybelline Dream Velvet Foundation', 'foundation', 'maybelline', 20, 18.49, 'This Maybelline Dream Velvet Foundation is a refreshing gel-whipped foundation that leaves complexion perfected and smooth with a velvety, soft-matte finish.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/24517c6c81c92eda31cd32b6327c1298_ra,w158,h184_pa,w158,h184.png', 'Natural Beige ','#E2B598');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(81,354, 'Maybelline Dream Velvet Foundation', 'foundation', 'maybelline', 20, 18.49, 'This Maybelline Dream Velvet Foundation is a refreshing gel-whipped foundation that leaves complexion perfected and smooth with a velvety, soft-matte finish.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/24517c6c81c92eda31cd32b6327c1298_ra,w158,h184_pa,w158,h184.png', 'Nude  ','#F1BEAB');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(82,354, 'Maybelline Dream Velvet Foundation', 'foundation', 'maybelline', 20, 18.49, 'This Maybelline Dream Velvet Foundation is a refreshing gel-whipped foundation that leaves complexion perfected and smooth with a velvety, soft-matte finish.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/24517c6c81c92eda31cd32b6327c1298_ra,w158,h184_pa,w158,h184.png', 'Porcelain Ivory ','#F8E0D4');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(83,354, 'Maybelline Dream Velvet Foundation', 'foundation', 'maybelline', 20, 18.49, 'This Maybelline Dream Velvet Foundation is a refreshing gel-whipped foundation that leaves complexion perfected and smooth with a velvety, soft-matte finish.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/24517c6c81c92eda31cd32b6327c1298_ra,w158,h184_pa,w158,h184.png', 'Pure Beige ','#EEBAA4');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(84,354, 'Maybelline Dream Velvet Foundation', 'foundation', 'maybelline', 20, 18.49, 'This Maybelline Dream Velvet Foundation is a refreshing gel-whipped foundation that leaves complexion perfected and smooth with a velvety, soft-matte finish.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/24517c6c81c92eda31cd32b6327c1298_ra,w158,h184_pa,w158,h184.png', 'Sandy Beige  ','#EFC2A1');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(85,354, 'Maybelline Dream Velvet Foundation', 'foundation', 'maybelline', 20, 18.49, 'This Maybelline Dream Velvet Foundation is a refreshing gel-whipped foundation that leaves complexion perfected and smooth with a velvety, soft-matte finish.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/24517c6c81c92eda31cd32b6327c1298_ra,w158,h184_pa,w158,h184.png', 'Warm Porcelain ','#FAE2D6');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(86,353, 'Maybelline Superstay Better Skin Foundation ', 'foundation', 'maybelline', 20, 14.99, 'The Maybelline Superstay Better Skin Foundation reduces the appearance of spots, bumps, dullness and redness to give you brighter, smoother and more even skin.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c7d967ef502ecd79ab7ab466c4952d82_ra,w158,h184_pa,w158,h184.png', 'Coconut  ','#9A6438');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(87,353, 'Maybelline Superstay Better Skin Foundation ', 'foundation', 'maybelline', 20, 14.99, 'The Maybelline Superstay Better Skin Foundation reduces the appearance of spots, bumps, dullness and redness to give you brighter, smoother and more even skin.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c7d967ef502ecd79ab7ab466c4952d82_ra,w158,h184_pa,w158,h184.png', 'Ivory ','#DCBCA3');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(88,353, 'Maybelline Superstay Better Skin Foundation ', 'foundation', 'maybelline', 20, 14.99, 'The Maybelline Superstay Better Skin Foundation reduces the appearance of spots, bumps, dullness and redness to give you brighter, smoother and more even skin.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c7d967ef502ecd79ab7ab466c4952d82_ra,w158,h184_pa,w158,h184.png', 'Porcelain ','#ECD3B2');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(89,353, 'Maybelline Superstay Better Skin Foundation ', 'foundation', 'maybelline', 20, 14.99, 'The Maybelline Superstay Better Skin Foundation reduces the appearance of spots, bumps, dullness and redness to give you brighter, smoother and more even skin.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c7d967ef502ecd79ab7ab466c4952d82_ra,w158,h184_pa,w158,h184.png', 'Rich Tan  ','#C99F6D');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(90,353, 'Maybelline Superstay Better Skin Foundation ', 'foundation', 'maybelline', 20, 14.99, 'The Maybelline Superstay Better Skin Foundation reduces the appearance of spots, bumps, dullness and redness to give you brighter, smoother and more even skin.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/c7d967ef502ecd79ab7ab466c4952d82_ra,w158,h184_pa,w158,h184.png', 'Sun Beige  ','#CA9B5F');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(91,339, 'Maybelline Dream Wonder Liquid Touch Foundation', 'foundation', 'maybelline', 20, 14.99, 'Maybelline Dream Wonder Liquid Touch Foundations breakthrough texture fuses with skin. A finish so impeccable, yet undetectable.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/ccb99ad6ac7f31a2a73454bdbda01d99_ra,w158,h184_pa,w158,h184.jpeg', 'Sun Beige (85) ','#DDA17B');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(92,321, 'Maybelline Dream Liquid Mousse', 'foundation', 'maybelline', 20, 14.79, 'Airbrushed perfection made possible:Air-whipped liquid makeup for 100% poreless skin Breakthrough finish cushions and smooths for the most flawless, luminous coverage\nLightweight air-whipped formula blends to virtually eliminate pores and imperfections Innovative shade-match pump makes finding your perfect shade a dream.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/1ca6a4a442b9aa6b5f3d94da77d8846c_ra,w158,h184_pa,w158,h184.png', 'Classic Ivory (Light 2) ','#FFD59E');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(93,321, 'Maybelline Dream Liquid Mousse', 'foundation', 'maybelline', 20, 14.79, 'Airbrushed perfection made possible:Air-whipped liquid makeup for 100% poreless skin Breakthrough finish cushions and smooths for the most flawless, luminous coverage\nLightweight air-whipped formula blends to virtually eliminate pores and imperfections Innovative shade-match pump makes finding your perfect shade a dream.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/1ca6a4a442b9aa6b5f3d94da77d8846c_ra,w158,h184_pa,w158,h184.png', 'Natural Beige (Medium 2.5) ','#CB9E6C');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(94,321, 'Maybelline Dream Liquid Mousse', 'foundation', 'maybelline', 20, 14.79, 'Airbrushed perfection made possible:Air-whipped liquid makeup for 100% poreless skin Breakthrough finish cushions and smooths for the most flawless, luminous coverage\nLightweight air-whipped formula blends to virtually eliminate pores and imperfections Innovative shade-match pump makes finding your perfect shade a dream.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/1ca6a4a442b9aa6b5f3d94da77d8846c_ra,w158,h184_pa,w158,h184.png', 'Natural Ivory (Light 3) ','#FFD9A6');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(95,321, 'Maybelline Dream Liquid Mousse', 'foundation', 'maybelline', 20, 14.79, 'Airbrushed perfection made possible:Air-whipped liquid makeup for 100% poreless skin Breakthrough finish cushions and smooths for the most flawless, luminous coverage\nLightweight air-whipped formula blends to virtually eliminate pores and imperfections Innovative shade-match pump makes finding your perfect shade a dream.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/1ca6a4a442b9aa6b5f3d94da77d8846c_ra,w158,h184_pa,w158,h184.png', 'Porcelain Ivory (Light 1) ','#FBD8AA');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(96,321, 'Maybelline Dream Liquid Mousse', 'foundation', 'maybelline', 20, 14.79, 'Airbrushed perfection made possible:Air-whipped liquid makeup for 100% poreless skin Breakthrough finish cushions and smooths for the most flawless, luminous coverage\nLightweight air-whipped formula blends to virtually eliminate pores and imperfections Innovative shade-match pump makes finding your perfect shade a dream.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/1ca6a4a442b9aa6b5f3d94da77d8846c_ra,w158,h184_pa,w158,h184.png', 'Pure Beige (Medium 2) ','#CE9E88');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(97,320, 'Maybelline FIT ME! Matte + Poreless Foundation', 'foundation', 'maybelline', 20, 10.99, 'Maybelline FIT ME! Matte + Poreless Foundation goes beyond skin tone matching to fit the unique texture issues of normal to oily skin for the ultimate natural skin fit.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/257993e12625cc45a72ec03636ffa5c5_ra,w158,h184_pa,w158,h184.jpg', 'Porcelain ','#fadbc7');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(98,320, 'Maybelline FIT ME! Matte + Poreless Foundation', 'foundation', 'maybelline', 20, 10.99, 'Maybelline FIT ME! Matte + Poreless Foundation goes beyond skin tone matching to fit the unique texture issues of normal to oily skin for the ultimate natural skin fit.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/257993e12625cc45a72ec03636ffa5c5_ra,w158,h184_pa,w158,h184.jpg', 'Natural Ivory ','#f1c7b1');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(99,320, 'Maybelline FIT ME! Matte + Poreless Foundation', 'foundation', 'maybelline', 20, 10.99, 'Maybelline FIT ME! Matte + Poreless Foundation goes beyond skin tone matching to fit the unique texture issues of normal to oily skin for the ultimate natural skin fit.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/257993e12625cc45a72ec03636ffa5c5_ra,w158,h184_pa,w158,h184.jpg', 'Ivory ','#e8b89b');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(100,320, 'Maybelline FIT ME! Matte + Poreless Foundation', 'foundation', 'maybelline', 20, 10.99, 'Maybelline FIT ME! Matte + Poreless Foundation goes beyond skin tone matching to fit the unique texture issues of normal to oily skin for the ultimate natural skin fit.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/257993e12625cc45a72ec03636ffa5c5_ra,w158,h184_pa,w158,h184.jpg', 'Classic Ivory ','#e6ba9f');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(101,320, 'Maybelline FIT ME! Matte + Poreless Foundation', 'foundation', 'maybelline', 20, 10.99, 'Maybelline FIT ME! Matte + Poreless Foundation goes beyond skin tone matching to fit the unique texture issues of normal to oily skin for the ultimate natural skin fit.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/257993e12625cc45a72ec03636ffa5c5_ra,w158,h184_pa,w158,h184.jpg', 'Nude Beige ','#e5b495');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(102,320, 'Maybelline FIT ME! Matte + Poreless Foundation', 'foundation', 'maybelline', 20, 10.99, 'Maybelline FIT ME! Matte + Poreless Foundation goes beyond skin tone matching to fit the unique texture issues of normal to oily skin for the ultimate natural skin fit.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/257993e12625cc45a72ec03636ffa5c5_ra,w158,h184_pa,w158,h184.jpg', 'Buff Beige ','#e2ae8e');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(103,320, 'Maybelline FIT ME! Matte + Poreless Foundation', 'foundation', 'maybelline', 20, 10.99, 'Maybelline FIT ME! Matte + Poreless Foundation goes beyond skin tone matching to fit the unique texture issues of normal to oily skin for the ultimate natural skin fit.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/257993e12625cc45a72ec03636ffa5c5_ra,w158,h184_pa,w158,h184.jpg', 'Natural Beige ','#dead87');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(104,320, 'Maybelline FIT ME! Matte + Poreless Foundation', 'foundation', 'maybelline', 20, 10.99, 'Maybelline FIT ME! Matte + Poreless Foundation goes beyond skin tone matching to fit the unique texture issues of normal to oily skin for the ultimate natural skin fit.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/257993e12625cc45a72ec03636ffa5c5_ra,w158,h184_pa,w158,h184.jpg', 'Pure Beige ','#dfa585');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(105,320, 'Maybelline FIT ME! Matte + Poreless Foundation', 'foundation', 'maybelline', 20, 10.99, 'Maybelline FIT ME! Matte + Poreless Foundation goes beyond skin tone matching to fit the unique texture issues of normal to oily skin for the ultimate natural skin fit.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/257993e12625cc45a72ec03636ffa5c5_ra,w158,h184_pa,w158,h184.jpg', 'Sun Beige ','#d9a37f');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(106,320, 'Maybelline FIT ME! Matte + Poreless Foundation', 'foundation', 'maybelline', 20, 10.99, 'Maybelline FIT ME! Matte + Poreless Foundation goes beyond skin tone matching to fit the unique texture issues of normal to oily skin for the ultimate natural skin fit.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/257993e12625cc45a72ec03636ffa5c5_ra,w158,h184_pa,w158,h184.jpg', 'Toffee ','#bc855f');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(107,320, 'Maybelline FIT ME! Matte + Poreless Foundation', 'foundation', 'maybelline', 20, 10.99, 'Maybelline FIT ME! Matte + Poreless Foundation goes beyond skin tone matching to fit the unique texture issues of normal to oily skin for the ultimate natural skin fit.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/257993e12625cc45a72ec03636ffa5c5_ra,w158,h184_pa,w158,h184.jpg', 'Coconut ','#b37750');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(108,317, 'Maybelline Fit Me Foundation with SPF', 'foundation', 'maybelline', 20, 10.99, 'It’s face makeup that fits you!Features: No oils, no waxes, no nonsenseNatural, Light to medium coverage that leaves skin the way it was meant to be.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/eccb88d484b8c929fd349b0995a5dba2_ra,w158,h184_pa,w158,h184.png', 'Ivory (115) ','#F7C2A5');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(109,317, 'Maybelline Fit Me Foundation w SPF', 'foundation', 'maybelline', 20, 10.99, 'It’s face makeup that fits you!Features: No oils, no waxes, no nonsenseNatural, Light to medium coverage that leaves skin the way it was meant to be.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/eccb88d484b8c929fd349b0995a5dba2_ra,w158,h184_pa,w158,h184.png', 'Classic Ivory (120) ','#EFC1A0');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(110,317, 'Maybelline Fit Me Foundation with SPF', 'foundation', 'maybelline', 20, 10.99, 'It’s face makeup that fits you!Features: No oils, no waxes, no nonsenseNatural, Light to medium coverage that leaves skin the way it was meant to be.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/eccb88d484b8c929fd349b0995a5dba2_ra,w158,h184_pa,w158,h184.png', 'Nude Beige (125) ','#E6B18F');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(111,317, 'Maybelline Fit Me Foundation w SPF', 'foundation', 'maybelline', 20, 10.99, 'It’s face makeup that fits you!Features: No oils, no waxes, no nonsenseNatural, Light to medium coverage that leaves skin the way it was meant to be.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/eccb88d484b8c929fd349b0995a5dba2_ra,w158,h184_pa,w158,h184.png', 'Natural Beige (220) ','#CE996F');
-- Maybelline Blush
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price],[Description],[Image],[ColourName],[HexValue]) values (112,439,'Maybelline Fit Me Blush','blush','maybelline',20,10.29,'Maybelline Fit Me Blush has lightweight pigments blend easily and wear evenly. It provides a natural, fade-proof cheek color that leaves skin the way it was meant to be...fresh, breathing, and natural. For Best Results: For soft, natural look, brush along cheekbone, sweeping upward.','https://d3t32hsnjxo7q6.cloudfront.net/i/53d5f825461117c0d96946e1029510b0_ra,w158,h184_pa,w158,h184.png','Deep Coral','#FB8684');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price],[Description],[Image],[ColourName],[HexValue]) values (113,439,'Maybelline Fit Me Blush','blush','maybelline',20,10.29,'Maybelline Fit Me Blush has lightweight pigments blend easily and wear evenly. It provides a natural, fade-proof cheek color that leaves skin the way it was meant to be...fresh, breathing, and natural. For Best Results: For soft, natural look, brush along cheekbone, sweeping upward.','https://d3t32hsnjxo7q6.cloudfront.net/i/53d5f825461117c0d96946e1029510b0_ra,w158,h184_pa,w158,h184.png','Deep Rose','#F27988');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(114,439, 'Maybelline Fit Me Blush', 'blush', 'maybelline', 20, 10.29, 'Maybelline Fit Me Blush has lightweight pigments blend easily and wear evenly. It provides a natural, fade-proof cheek color that leaves skin the way it was meant to be...fresh, breathing, and natural.For Best Results: For soft, natural look, brush along cheekbone, sweeping upward.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/53d5f825461117c0d96946e1029510b0_ra,w158,h184_pa,w158,h184.png', 'Deep Wine ','#C94A50');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(115,439, 'Maybelline Fit Me Blush', 'blush', 'maybelline', 20, 10.29, 'Maybelline Fit Me Blush has lightweight pigments blend easily and wear evenly. It provides a natural, fade-proof cheek color that leaves skin the way it was meant to be...fresh, breathing, and natural.For Best Results: For soft, natural look, brush along cheekbone, sweeping upward.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/53d5f825461117c0d96946e1029510b0_ra,w158,h184_pa,w158,h184.png', 'Light Rose ','#FFAAAF');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(116,439, 'Maybelline Fit Me Blush', 'blush', 'maybelline', 20, 10.29, 'Maybelline Fit Me Blush has lightweight pigments blend easily and wear evenly. It provides a natural, fade-proof cheek color that leaves skin the way it was meant to be...fresh, breathing, and natural.For Best Results: For soft, natural look, brush along cheekbone, sweeping upward.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/53d5f825461117c0d96946e1029510b0_ra,w158,h184_pa,w158,h184.png', 'Medium Coral  ','#FC9D8F');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(117,439, 'Maybelline Fit Me Blush', 'blush', 'maybelline', 20, 10.29, 'Maybelline Fit Me Blush has lightweight pigments blend easily and wear evenly. It provides a natural, fade-proof cheek color that leaves skin the way it was meant to be...fresh, breathing, and natural.For Best Results: For soft, natural look, brush along cheekbone, sweeping upward.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/53d5f825461117c0d96946e1029510b0_ra,w158,h184_pa,w158,h184.png', 'Medium Nude ','#E89890');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(118,439, 'Maybelline Fit Me Blush', 'blush', 'maybelline', 20, 10.29, 'Maybelline Fit Me Blush has lightweight pigments blend easily and wear evenly. It provides a natural, fade-proof cheek color that leaves skin the way it was meant to be...fresh, breathing, and natural.For Best Results: For soft, natural look, brush along cheekbone, sweeping upward.', 'https://d3t32hsnjxo7q6.cloudfront.net/i/53d5f825461117c0d96946e1029510b0_ra,w158,h184_pa,w158,h184.png', 'Medium Pink ','#FF93A0');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(119,414, 'Maybelline Dream Bouncy Blush', 'blush', 'maybelline', 20, 11.99, 'Now, blush has bounce! Freshest flush ever:• New bouncy texture is formulated with silicone elastomers• Lightweight like a powder, yet melts seamlessly into skin like a cream giving you a fresh flush• Dermatologist tested• Allergy tested• Non-comedogenic', 'https://d3t32hsnjxo7q6.cloudfront.net/i/51eacb9efebbaee39399e65ffe3d9416_ra,w158,h184_pa,w158,h184.png', 'Fresh Pink ','#ecc3d5');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(120,414, 'Maybelline Dream Bouncy Blush', 'blush', 'maybelline', 20, 11.99, 'Now, blush has bounce! Freshest flush ever:• New bouncy texture is formulated with silicone elastomers• Lightweight like a powder, yet melts seamlessly into skin like a cream giving you a fresh flush• Dermatologist tested• Allergy tested• Non-comedogenic', 'https://d3t32hsnjxo7q6.cloudfront.net/i/51eacb9efebbaee39399e65ffe3d9416_ra,w158,h184_pa,w158,h184.png', 'Hot Tamale ','#ee9cb1');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(121, 414, 'Maybelline Dream Bouncy Blush', 'blush', 'maybelline', 20, 11.99, 'Now, blush has bounce! Freshest flush ever:• New bouncy texture is formulated with silicone elastomers• Lightweight like a powder, yet melts seamlessly into skin like a cream giving you a fresh flush• Dermatologist tested• Allergy tested• Non-comedogenic', 'https://d3t32hsnjxo7q6.cloudfront.net/i/51eacb9efebbaee39399e65ffe3d9416_ra,w158,h184_pa,w158,h184.png', 'Peach Satin ','#ecbaba');
INSERT INTO [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) VALUES(122,414, 'Maybelline Dream Bouncy Blush', 'blush', 'maybelline', 20, 11.99, 'Now, blush has bounce! Freshest flush ever:• New bouncy texture is formulated with silicone elastomers• Lightweight like a powder, yet melts seamlessly into skin like a cream giving you a fresh flush• Dermatologist tested• Allergy tested• Non-comedogenic', 'https://d3t32hsnjxo7q6.cloudfront.net/i/51eacb9efebbaee39399e65ffe3d9416_ra,w158,h184_pa,w158,h184.png', 'Plum Wine ','#c25159');

set identity_insert [Products] off