

set identity_insert [Products] on


/*
Lipsticks
*/
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,97,'Maybelline Color Sensational Vivid Matte Liquid Lip Colour','lipstick','maybelline',20,12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. \nFormula is comfortable and creamy with a smooth feel upon application. \nWith full color coverage, the result is a rich, intense lip look in a \nrange of colors from Nude Flush to Electric Pink to Vivid Violet.Features: Lip color glides on smooth to a matte finishInfused with pure pigments for high-impact colorCreamy liquid base for a soft, cushiony feel.','https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png','Nude Thrill','#AC7773');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,97,'Maybelline Color Sensational Vivid Matte Liquid Lip Colour','lipstick','maybelline',20,12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. \nFormula is comfortable and creamy with a smooth feel upon application. \nWith full color coverage, the result is a rich, intense lip look in a \nrange of colors from Nude Flush to Electric Pink to Vivid Violet.Features: Lip color glides on smooth to a matte finishInfused with pure pigments for high-impact colorCreamy liquid base for a soft, cushiony feel.','https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png','Nude Flush','#BD7A80');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,97,'Maybelline Color Sensational Vivid Matte Liquid Lip Colour','lipstick','maybelline',20,12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. \nFormula is comfortable and creamy with a smooth feel upon application. \nWith full color coverage, the result is a rich, intense lip look in a \nrange of colors from Nude Flush to Electric Pink to Vivid Violet.Features: Lip color glides on smooth to a matte finishInfused with pure pigments for high-impact colorCreamy liquid base for a soft, cushiony feel.','https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png','Pink Charge','#D65F84');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,97,'Maybelline Color Sensational Vivid Matte Liquid Lip Colour','lipstick','maybelline',20,12.99, 'Bold, vivid color glides easily onto lips for a velvety matte finish with Maybelline Color Sensational Vivid Matte Liquid Lip Colour. \nFormula is comfortable and creamy with a smooth feel upon application. \nWith full color coverage, the result is a rich, intense lip look in a \nrange of colors from Nude Flush to Electric Pink to Vivid Violet.Features: Lip color glides on smooth to a matte finishInfused with pure pigments for high-impact colorCreamy liquid base for a soft, cushiony feel.','https://d3t32hsnjxo7q6.cloudfront.net/i/d0b6855d9b603a00f776de498c971b88_ra,w158,h184_pa,w158,h184.png','Electric Pink','#D73D8C');
-- Maybelline eyeshadow
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType][Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,291,'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather','eyeshadow','Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their most intense, long-lasting colour saturation. The cream formula glides on without creasing and keeps colour vibrant.Ophthalmologist-tested. Safe for sensitive eyes and contact lens wearers. For best results: With fingertips, sweep all over eye from inner corner and work outwards. For added drama, darken as desired. ','https://d3t32hsnjxo7q6.cloudfront.net/i/c2ddacc79f4fdd3d23664581c76546bc_ra,w158,h184_pa,w158,h184.png','Bad to the Bronze','#ab897d');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,291,'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather','eyeshadow','Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their most intense, long-lasting colour saturation. The cream formula glides on without creasing and keeps colour vibrant.Ophthalmologist-tested. Safe for sensitive eyes and contact lens wearers. For best results: With fingertips, sweep all over eye from inner corner and work outwards. For added drama, darken as desired. ','https://d3t32hsnjxo7q6.cloudfront.net/i/c2ddacc79f4fdd3d23664581c76546bc_ra,w158,h184_pa,w158,h184.png','Tenacious Teal','#1d8493');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,291,'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather','eyeshadow','Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their most intense, long-lasting colour saturation. The cream formula glides on without creasing and keeps colour vibrant.Ophthalmologist-tested. Safe for sensitive eyes and contact lens wearers. For best results: With fingertips, sweep all over eye from inner corner and work outwards. For added drama, darken as desired. ','https://d3t32hsnjxo7q6.cloudfront.net/i/c2ddacc79f4fdd3d23664581c76546bc_ra,w158,h184_pa,w158,h184.png','Too Cool','#d3cfcc');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,291,'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather','eyeshadow','Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their most intense, long-lasting colour saturation. The cream formula glides on without creasing and keeps colour vibrant.Ophthalmologist-tested. Safe for sensitive eyes and contact lens wearers. For best results: With fingertips, sweep all over eye from inner corner and work outwards. For added drama, darken as desired. ','https://d3t32hsnjxo7q6.cloudfront.net/i/c2ddacc79f4fdd3d23664581c76546bc_ra,w158,h184_pa,w158,h184.png','Tough as Taupe','#81726D');
/*
Maybelline eyeliners
*/
insert into [Products] ([ProductID],[API_ID],[ProductName],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,232,'Maybelline Line Express Eyeliner','maybelline',20,7.29, 'Maybelline Line Express Eyeliner"s intense color formula + smart tip smudger makes this liner glide on smoothly and is easy to apply with just one stroke.Features: Creamy formula delivers intense colorContour smudger makes blending easyAll-day wearSafe for sensitive eyes and ophthalmologist-testedContact lens safe','https://d3t32hsnjxo7q6.cloudfront.net/i/4e88f928ad91c88e2ecb8596431ce799_ra,w158,h184_pa,w158,h184.png','','');
insert into [Products] ([ProductID],[API_ID],[ProductName],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,229,'Maybelline Unstoppable Eyeline','maybelline',20,8.99, 'Unstoppable Eyeliner allows ultra-smooth application for defined lines and eyes.\nIt is a self-sharpening mechanical pencil, and will hold your look in place all day long.\nWaterproof.\nOphthalmologist tested, contact lens safe for sensitive eyes.\n','https://d3t32hsnjxo7q6.cloudfront.net/i/bab89a9fe13b34235e0dd1f4f44c05cf_ra,w158,h184_pa,w158,h184.png','Onyx ','#736364');
insert into [Products] ([ProductID],[API_ID],[ProductName],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,229,'Maybelline Unstoppable Eyeline','maybelline',20,8.99, 'Unstoppable Eyeliner allows ultra-smooth application for defined lines and eyes.\nIt is a self-sharpening mechanical pencil, and will hold your look in place all day long.\nWaterproof.\nOphthalmologist tested, contact lens safe for sensitive eyes.\n','https://d3t32hsnjxo7q6.cloudfront.net/i/bab89a9fe13b34235e0dd1f4f44c05cf_ra,w158,h184_pa,w158,h184.png','Pewter ','#797B7D');

-- Maybelline Blush
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price],[Description],[Image],[ColourName],[HexValue]) values (,439,'Maybelline Fit Me Blush','blush','maybelline',20,10.29,'Maybelline Fit Me Blush has lightweight pigments blend easily and wear evenly. It provides a natural, fade-proof cheek color that leaves skin the way it was meant to be...fresh, breathing, and natural.\n\nFor Best Results: For soft, natural look, brush along cheekbone, sweeping upward.','https://d3t32hsnjxo7q6.cloudfront.net/i/53d5f825461117c0d96946e1029510b0_ra,w158,h184_pa,w158,h184.png','Deep Coral','#FB8684');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price],[Description],[Image],[ColourName],[HexValue]) values (,439,'Maybelline Fit Me Blush','blush','maybelline',20,10.29,'Maybelline Fit Me Blush has lightweight pigments blend easily and wear evenly. It provides a natural, fade-proof cheek color that leaves skin the way it was meant to be...fresh, breathing, and natural.\n\nFor Best Results: For soft, natural look, brush along cheekbone, sweeping upward.','https://d3t32hsnjxo7q6.cloudfront.net/i/53d5f825461117c0d96946e1029510b0_ra,w158,h184_pa,w158,h184.png','Deep Rose','#F27988');
set identity_insert [Products] off

