USE [Reimbursement];
GO

set identity_insert [Products] on
-- Maybelline eyeshadow
insert into [Products] ([ProductID],[API_ID],[ProductName],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,309,'Maybelline Expert Wear Eye Shadow Quad ','maybelline',20,8.99, 'Easy to use, lots to choose!Maybelline Expert Wear Eye Shadow \nQuads have 4 coordinating shades with step by step application guide \nmakes shadow easier than ever. The eyeshadows glide on effortlessly with\n superior smoothness and the velvet-tip applicator blends without \ntugging or pulling. Safe for sensitive eyes and contact lens wearers, \nophthalmologist-tested.For best results sweep the brush 4 times:Apply base color. Sweep shade on lid. Contour crease and blend. Line around eye.','https://d3t32hsnjxo7q6.cloudfront.net/i/c924006882e8e313d445a3a5394e4729_ra,w158,h184_pa,w158,h184.png','Audacious Asphalt','#515552');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType][Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,291,'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather','eyeshadow','Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their most intense, long-lasting colour saturation. The cream formula glides on without creasing and keeps colour vibrant.Ophthalmologist-tested. Safe for sensitive eyes and contact lens wearers. For best results: With fingertips, sweep all over eye from inner corner and work outwards. For added drama, darken as desired. ','https://d3t32hsnjxo7q6.cloudfront.net/i/c2ddacc79f4fdd3d23664581c76546bc_ra,w158,h184_pa,w158,h184.png','Bad to the Bronze','#ab897d');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,291,'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather','eyeshadow','Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their most intense, long-lasting colour saturation. The cream formula glides on without creasing and keeps colour vibrant.Ophthalmologist-tested. Safe for sensitive eyes and contact lens wearers. For best results: With fingertips, sweep all over eye from inner corner and work outwards. For added drama, darken as desired. ','https://d3t32hsnjxo7q6.cloudfront.net/i/c2ddacc79f4fdd3d23664581c76546bc_ra,w158,h184_pa,w158,h184.png','Tenacious Teal','#1d8493');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,291,'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather','eyeshadow','Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their most intense, long-lasting colour saturation. The cream formula glides on without creasing and keeps colour vibrant.Ophthalmologist-tested. Safe for sensitive eyes and contact lens wearers. For best results: With fingertips, sweep all over eye from inner corner and work outwards. For added drama, darken as desired. ','https://d3t32hsnjxo7q6.cloudfront.net/i/c2ddacc79f4fdd3d23664581c76546bc_ra,w158,h184_pa,w158,h184.png','Too Cool','#d3cfcc');
insert into [Products] ([ProductID],[API_ID],[ProductName],[ProductType],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,291,'Maybelline Eye Studio Color Tattoo 24HR Cream Gel Shadow Leather','eyeshadow','Dare to wear 24HR shadow!Maybellines Color Tattoo Cream Gel Shadow uses ink technology for their most intense, long-lasting colour saturation. The cream formula glides on without creasing and keeps colour vibrant.Ophthalmologist-tested. Safe for sensitive eyes and contact lens wearers. For best results: With fingertips, sweep all over eye from inner corner and work outwards. For added drama, darken as desired. ','https://d3t32hsnjxo7q6.cloudfront.net/i/c2ddacc79f4fdd3d23664581c76546bc_ra,w158,h184_pa,w158,h184.png','Tough as Taupe','#81726D');
/*
Maybelline eyeliners
*/
insert into [Products] ([ProductID],[API_ID],[ProductName],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,232,'Maybelline Line Express Eyeliner','maybelline',20,7.29, 'Maybelline Line Express Eyeliner"s intense color formula + smart tip smudger makes this liner glide on smoothly and is easy to apply with just one stroke.Features: Creamy formula delivers intense colorContour smudger makes blending easyAll-day wearSafe for sensitive eyes and ophthalmologist-testedContact lens safe','https://d3t32hsnjxo7q6.cloudfront.net/i/4e88f928ad91c88e2ecb8596431ce799_ra,w158,h184_pa,w158,h184.png','','');
insert into [Products] ([ProductID],[API_ID],[ProductName],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,229,'Maybelline Unstoppable Eyeline','maybelline',20,8.99, 'Unstoppable Eyeliner allows ultra-smooth application for defined lines and eyes.\nIt is a self-sharpening mechanical pencil, and will hold your look in place all day long.\nWaterproof.\nOphthalmologist tested, contact lens safe for sensitive eyes.\n','https://d3t32hsnjxo7q6.cloudfront.net/i/bab89a9fe13b34235e0dd1f4f44c05cf_ra,w158,h184_pa,w158,h184.png','Onyx ','#736364');
insert into [Products] ([ProductID],[API_ID],[ProductName],[Brand],[Inventory],[Price], [Description],[Image],[ColourName],[HexValue]) values (,229,'Maybelline Unstoppable Eyeline','maybelline',20,8.99, 'Unstoppable Eyeliner allows ultra-smooth application for defined lines and eyes.\nIt is a self-sharpening mechanical pencil, and will hold your look in place all day long.\nWaterproof.\nOphthalmologist tested, contact lens safe for sensitive eyes.\n','https://d3t32hsnjxo7q6.cloudfront.net/i/bab89a9fe13b34235e0dd1f4f44c05cf_ra,w158,h184_pa,w158,h184.png','Pewter ','#797B7D');
set identity_insert [Products] off