#build stage
FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build

WORKDIR /source

COPY . .

RUN dotnet restore "./ECommerce.API.sln"

RUN dotnet publish "./ECommerce.API.sln" -c release -o /app --no-restore

#Serve stage

FROM  mcr.microsoft.com/dotnet/sdk:6.0-focal

WORKDIR /app

COPY --from=build /app ./



ENTRYPOINT ["dotnet", "ECommerce.API.dll"]

